name: htracking
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pytorch=2.2.0
  - torchvision=0.17.0
  - torchaudio=2.2.0
  - cpuonly                # Enables MPS on macOS
  - ultralytics>=8.2
  - opencv
  - ffmpeg
  - mplsoccer
  - streamlit
  - pip
  - pip:
      - numpy<2.0           # Patch for PyTorch+NumPy incompatibility
      - loguru              # Required by ByteTrack utils
      - tracklab
      - kloppy
      - SoccerNet
      # Do NOT include ByteTrack here
